image: Visual Studio 2019

install:
  - cinst qbs
  - qbs setup-toolchains --type msvc
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\cl.exe"
      MSVC2019-x64
  - cd %APPVEYOR_BUILD_FOLDER%
      && git submodule update --init --recursive

build_script:
  - qbs
      build profile:MSVC2019-x64 --file rec_cpp.qbs --build-directory %TMP%/build
      -p autotest-runner
