jobs:
  - job: Windows_msvc2019
    pool:
      vmImage: windows-2019
    steps:
      - script: choco install qbs
      - script: qbs setup-toolchains --detect
      - script: qbs config --list profiles
      - checkout: self
        submodules: true
      - script: qbs
            build profile:MSVC2019-x64 --file rec_cpp.qbs --build-directory %TMP%\build
            -p autotest-runner

  - job: Linux_docker_clang8
    pool:
      vmImage: ubuntu-16.04
    steps:
      - checkout: self
        submodules: true
      - script:
          docker run -t -v${PWD}:/build -e TERM=xterm-color -e GTEST_COLOR=yes
            arbmind/qbs-clang8:1
            build --file /build/rec_cpp.qbs --build-directory /tmp/build
            -p autotest-runner
            modules.cpp.commonCompilerFlags:-fcolor-diagnostics
