namespace REC.AST
{
    // Expression is the base class for all AST nodes
    // The AST represents the interpreted text
    // generated by the Parser
    // used for Code generation and evaluation
    public interface IExpression
    {
        // range of the entire expression
        // generated expressions use null
        TextFileRange Range { get; }
    }

    abstract class Expression : IExpression
    {
        public TextFileRange Range { get; set; }
    }
}
