name: Test Runner

on: push

jobs:
  docker-qbs:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux Docker: Clang 13, Qbs 1.20.1"
            os: ubuntu-20.04
            image: arbmind/qbs-clang13:qbs_v1.20.1

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build and Run Tests
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/build -w /build
          ${{ matrix.image }}
          build
          --file rec_cpp.qbs
          --build-directory /tmp/build
          -p autotest-runner

  windows-qbs:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows: MSVC 2019"
            os: windows-2019
            vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qbs_url: "https://download.qt.io/official_releases/qbs/1.21.0/qbs-windows-x86_64-1.21.0.zip"
          - name: "Windows: MSVC 2022"
            os: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qbs_url: "https://download.qt.io/official_releases/qbs/1.21.0/qbs-windows-x86_64-1.21.0.zip"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Qbs
        shell: cmake -P {0}
        run: file(DOWNLOAD "${{ matrix.qbs_url }}" ./qbs.zip)

      - name: Install Qbs
        run: |
          7z x qbs.zip -oqbs
          echo "${{ github.workspace }}/qbs/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup Qbs Toolchain
        run: qbs setup-toolchains --type msvc $(cmd /c '"${{ matrix.vcvars }}" >nul & where cl') msvc

      - name: Build and Run Tests
        run: >-
          qbs build profile:msvc
          --file rec_cpp.qbs
          --build-directory ${env:RUNNER_TEMP}\build
          -p autotest-runner
